# Generated by Django 5.1.3 on 2024-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.TextField(max_length=255)),
                ('descricao_produto', models.TextField(max_length=255)),
            ],
        ),
    ]
