# Generated by Django 5.1.3 on 2024-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_imagem_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
