# Generated by Django 5.1.3 on 2024-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('verdureira', 'Verdureira'), ('acougue', 'Açougue'), ('limpeza', 'Limpeza'), ('frios', 'Frios'), ('bebidas', 'Bebidas')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
