# Generated by Django 5.1.3 on 2025-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
