# Generated by Django 5.1.3 on 2025-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateField(),
        ),
    ]
